apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
   - rolearn: arn:aws:iam::162198556136:role/eks-test20201210090309559900000009
     username: system:node:{{EC2PrivateDNSName}}
     groups:
      - system:bootstrappers
      - system:nodes
