
repositories:
- name: stable
  url: https://charts.helm.sh/stable

helmDefaults:
  tillerless: true
  verify: false
  wait: true
  timeout: 600
  force: true


releases:
# helm install metrics-server \
# stable/metrics-server --version 2.8.2 \
#--namespace kube-system -f charts/metrics-server/values.yaml
- name: metrics-server
  chart: stable/metrics-server
  namespace: kube-system
  version: 2.8.2
  values:
  - "./charts/metrics-server/values.yaml"

- name: cluster-autoscaler
  chart: stable/cluster-autoscaler
  version: 7.1.0
  namespace: kube-system
  values:
  - "./charts/cluster-autoscaler/values.yaml"
